//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategID { get; set; }
    
        public virtual Category1 Category { get; set; }
    }
}
